### ISSUE TITLE
I'm facing this mongodb issue when I start the bot on koyeb but and there is no response on WhatsApp 

### ISSUE THREAD

**Issue by osemudiamiel** [Guru322/GURU-BOT#397]
MongooseError: Operation `datas.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) unhandledRejection
MongooseError: Operation `datas.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) unhandledRejection
MongooseError: Operation `datas.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) unhandledRejection

ERROR  [Tue, 25 Jun 2024 09:30:57 GMT]: 
connection closed....Get a New Session
Error: Connection Closed
    at sendRawMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:59:19)
    at sendNode (/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:78:16)
    at query (/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:142:15)
    at getUSyncDevices (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:166:30)
    at /node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:358:53
    at Object.transaction (/node_modules/@whiskeysockets/baileys/lib/Utils/auth-utils.js:136:32)
    at relayMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:280:30)
    at Object.sendMessage (/node_modules/@whiskeysockets/baileys/lib/Socket/messages-send.js:654:23) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {

**Comment by Guru322** [comment]
> MongooseError: Operation `datas.findOne()` buffering timed out after 10000ms at Timeout. (/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23) at listOnTimeout (node:internal/timers:573:17) at process.processTimers (node:internal/timers:514:7) unhandledRejection MongooseError: Operation `datas.findOne()` buffering timed out after 10000ms at Timeout. (/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23) at listOnTimeout (node:internal/timers:573:17) at process.processTimers (node:internal/timers:514:7) unhandledRejection MongooseError: Operation `datas.findOne()` buffering timed out after 10000ms at Timeout. (/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:185:23) at listOnTimeout (node:internal/timers:573:17) at process.processTimers (node:internal/timers:514:7) unhandledRejection
> 


your Mongodb connection password is wrong
